### PR TITLE
task 15

### PR DESCRIPTION
**Pull request by lesharadkovich**
Might be not the best solution, but it works :)

### CODE REVIEW

**Review by Alexander-Shein — COMMENTED** [review]
Yes, not the best solution :)
Try COUNT function and CASE ... WHEN
https://stackoverflow.com/questions/17975229/using-sql-count-in-a-case-statement

**Comment by lesharadkovich** [comment]
Thanks for link :)

**Review by Alexander-Shein — COMMENTED** [review]
And you forgot to filter data by year :) in 1997

**Comment by lesharadkovich** [comment]
Done

**Review by Alexander-Shein — COMMENTED** [review]
Perfect!

**Pull request closed without merging**
