### PR TITLE
task 13

### PR DESCRIPTION
**Pull request by lesharadkovich**

### CODE REVIEW

**Review by Alexander-Shein — COMMENTED** [review]
Please try with nested query without union

**Review by Alexander-Shein — COMMENTED** [review]
Try with only 1 nested query :)
Or with CASE ...WHEN..

**Review by Alexander-Shein — COMMENTED** [review]
Do we need distinc here?

**Comment by lesharadkovich** [comment]
No, we dont :)

**Review by Alexander-Shein — COMMENTED** [review]
Well done!

**Pull request closed without merging**
