### PR TITLE
Task18

### PR DESCRIPTION
**Pull request by FedorovD**

### CODE REVIEW

**Review by Alexander-Shein — COMMENTED** [review]
Ok you learned functions :)
And now try to use group by clause.

**Comment by FedorovD** [comment]
I corrected some thing but what means use group by clause?

**Review by Alexander-Shein — COMMENTED** [review]
I mean remove your query and try again. Don't use functions. You can solve this through GROUP BY

**Comment by FedorovD** [comment]
Do I need to output data for each day in a year or just days where was some orders?

**Review by Alexander-Shein — COMMENTED** [review]
Days where we have orders

**Review by Alexander-Shein — COMMENTED** [review]
Good job

**Pull request closed without merging**
